[2024-06-15T20:50:37.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T20:50:37.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_api.format_reponse manual__2024-06-15T20:48:04.596054+00:00 [queued]>
[2024-06-15T20:50:37.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_api.format_reponse manual__2024-06-15T20:48:04.596054+00:00 [queued]>
[2024-06-15T20:50:37.426+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-15T20:50:37.610+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): format_reponse> on 2024-06-15 20:48:04.596054+00:00
[2024-06-15T20:50:37.626+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6766) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-15T20:50:37.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_api', 'format_reponse', 'manual__2024-06-15T20:48:04.596054+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/random_api_request_w.py', '--cfg-path', '/tmp/tmpum2u5biv']
[2024-06-15T20:50:37.629+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask format_reponse
[2024-06-15T20:50:37.629+0000] {standard_task_runner.py:63} INFO - Started process 6780 to run task
[2024-06-15T20:50:37.738+0000] {task_command.py:426} INFO - Running <TaskInstance: random_api.format_reponse manual__2024-06-15T20:48:04.596054+00:00 [running]> on host d4d3ae2e009b
[2024-06-15T20:50:38.062+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='random_api' AIRFLOW_CTX_TASK_ID='format_reponse' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T20:48:04.596054+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T20:48:04.596054+00:00'
[2024-06-15T20:50:38.065+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T20:50:38.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T20:50:38.089+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: format_reponse() missing 1 required positional argument: 'res'
[2024-06-15T20:50:38.106+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=random_api, task_id=format_reponse, run_id=manual__2024-06-15T20:48:04.596054+00:00, execution_date=20240615T204804, start_date=20240615T205037, end_date=20240615T205038
[2024-06-15T20:50:38.161+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task format_reponse (format_reponse() missing 1 required positional argument: 'res'; 6780)
[2024-06-15T20:50:38.209+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-15T20:50:38.256+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T20:50:38.352+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
