[2024-06-15T21:14:31.613+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T21:14:31.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rand_request.load_to_s3 manual__2024-06-15T21:09:54.698888+00:00 [queued]>
[2024-06-15T21:14:31.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rand_request.load_to_s3 manual__2024-06-15T21:09:54.698888+00:00 [queued]>
[2024-06-15T21:14:31.656+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-15T21:14:31.812+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-06-15 21:09:54.698888+00:00
[2024-06-15T21:14:31.824+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-15T21:14:31.826+0000] {standard_task_runner.py:63} INFO - Started process 8322 to run task
[2024-06-15T21:14:31.824+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'rand_request', 'load_to_s3', 'manual__2024-06-15T21:09:54.698888+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/rand.py', '--cfg-path', '/tmp/tmpif_hplr7']
[2024-06-15T21:14:31.829+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask load_to_s3
[2024-06-15T21:14:31.933+0000] {task_command.py:426} INFO - Running <TaskInstance: rand_request.load_to_s3 manual__2024-06-15T21:09:54.698888+00:00 [running]> on host d4d3ae2e009b
[2024-06-15T21:14:32.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='rand_request' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T21:09:54.698888+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T21:09:54.698888+00:00'
[2024-06-15T21:14:32.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T21:14:32.398+0000] {base.py:84} INFO - Using connection ID 'simple_store' for task execution.
[2024-06-15T21:14:32.400+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='simple_store', conn_type='aws') credentials retrieved from login and password.
[2024-06-15T21:14:36.376+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-15T21:14:36.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T21:14:36.396+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=rand_request, task_id=load_to_s3, run_id=manual__2024-06-15T21:09:54.698888+00:00, execution_date=20240615T210954, start_date=20240615T211431, end_date=20240615T211436
[2024-06-15T21:14:36.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-15T21:14:36.612+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T21:14:36.660+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
