[2024-06-17T09:12:07.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T09:12:07.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T09:02:01.724998+00:00 [queued]>
[2024-06-17T09:12:07.801+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T09:02:01.724998+00:00 [queued]>
[2024-06-17T09:12:07.802+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-06-17T09:12:07.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-06-17 09:02:01.724998+00:00
[2024-06-17T09:12:07.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-06-17T09:02:01.724998+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/postgres_s3.py', '--cfg-path', '/tmp/tmpyk7xtbb7']
[2024-06-17T09:12:07.996+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6139) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T09:12:07.998+0000] {standard_task_runner.py:63} INFO - Started process 6157 to run task
[2024-06-17T09:12:07.998+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask load_to_s3
[2024-06-17T09:12:08.190+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T09:02:01.724998+00:00 [running]> on host dc64bc371a82
[2024-06-17T09:12:08.751+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='protectorateog@gmail.com' AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T09:02:01.724998+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T09:02:01.724998+00:00'
[2024-06-17T09:12:08.753+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T09:12:08.792+0000] {base.py:84} INFO - Using connection ID 'post_s3' for task execution.
[2024-06-17T09:12:08.824+0000] {base.py:84} INFO - Using connection ID 'simple_store' for task execution.
[2024-06-17T09:12:08.825+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='simple_store', conn_type='aws') credentials retrieved from login and password.
[2024-06-17T09:12:12.099+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-17T09:12:12.101+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T09:12:12.114+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-06-17T09:02:01.724998+00:00, execution_date=20240617T090201, start_date=20240617T091207, end_date=20240617T091212
[2024-06-17T09:12:12.203+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T09:12:12.227+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T09:12:12.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
