[2024-06-17T09:13:07.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T09:13:07.731+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T08:56:08.856496+00:00 [queued]>
[2024-06-17T09:13:07.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T08:56:08.856496+00:00 [queued]>
[2024-06-17T09:13:07.749+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-06-17T09:13:07.815+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-06-17 08:56:08.856496+00:00
[2024-06-17T09:13:07.829+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T09:13:07.831+0000] {standard_task_runner.py:63} INFO - Started process 6233 to run task
[2024-06-17T09:13:07.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-06-17T08:56:08.856496+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/postgres_s3.py', '--cfg-path', '/tmp/tmp0xdaqlvd']
[2024-06-17T09:13:07.832+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask load_to_s3
[2024-06-17T09:13:07.958+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-17T08:56:08.856496+00:00 [running]> on host dc64bc371a82
[2024-06-17T09:13:13.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='protectorateog@gmail.com' AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T08:56:08.856496+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T08:56:08.856496+00:00'
[2024-06-17T09:13:13.450+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T09:13:13.497+0000] {base.py:84} INFO - Using connection ID 'post_s3' for task execution.
[2024-06-17T09:13:13.523+0000] {base.py:84} INFO - Using connection ID 'simple_store' for task execution.
[2024-06-17T09:13:13.524+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='simple_store', conn_type='aws') credentials retrieved from login and password.
[2024-06-17T09:13:16.894+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-17T09:13:16.896+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T09:13:16.909+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-06-17T08:56:08.856496+00:00, execution_date=20240617T085608, start_date=20240617T091307, end_date=20240617T091316
[2024-06-17T09:13:18.093+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T09:13:18.115+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T09:13:18.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
