[2024-06-17T09:09:51.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T09:09:51.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-17T09:09:37.121128+00:00 [queued]>
[2024-06-17T09:09:51.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-17T09:09:37.121128+00:00 [queued]>
[2024-06-17T09:09:51.952+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-17T09:09:52.099+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-06-17 09:09:37.121128+00:00
[2024-06-17T09:09:52.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5924) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T09:09:52.142+0000] {standard_task_runner.py:63} INFO - Started process 5939 to run task
[2024-06-17T09:09:52.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_postgres', 'manual__2024-06-17T09:09:37.121128+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/postgres_s3.py', '--cfg-path', '/tmp/tmp4kexue54']
[2024-06-17T09:09:52.149+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask load_to_postgres
[2024-06-17T09:09:52.391+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-17T09:09:37.121128+00:00 [running]> on host dc64bc371a82
[2024-06-17T09:09:53.090+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='protectorateog@gmail.com' AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T09:09:37.121128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T09:09:37.121128+00:00'
[2024-06-17T09:09:53.108+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T09:09:53.814+0000] {base.py:84} INFO - Using connection ID 'post_s3' for task execution.
[2024-06-17T09:09:54.072+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-17T09:09:54.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T09:09:54.088+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_postgres, run_id=manual__2024-06-17T09:09:37.121128+00:00, execution_date=20240617T090937, start_date=20240617T090951, end_date=20240617T090954
[2024-06-17T09:09:54.239+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T09:09:54.275+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-17T09:09:54.571+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
